@api = http://localhost:6000/api/materias

### get all elements
{{api}}

### get element
{{api}}/621133db348a1464fe84d70d

### add an element
POST {{api}}
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGVjNDJlODZiZTE2NzlkNmNmMDg2NjEiLCJpYXQiOjE2MzEwNTIyNTAsImV4cCI6MTYzMTA2NjY1MH0.saezcg3G3uvinlCbs_E_zC9zOvVls_Dy2-6XrZeZBqM

{
    "nombre" : "Astronomia"
}

### update element
PUT {{api}}/621133db348a1464fe84d70d
Content-Type: application/json

{
    "nombre" : "Astroworld"
}

### delete element 
DELETE {{api}}/621133db348a1464fe84d70d